twitch-game/twitch-game.ui/Controllers/PersonneController.cs
using Microsoft.AspNetCore.Mvc;
using twitch.ui.Models;
using twitch.api;
using AutoMapper;
using Microsoft.EntityFrameworkCore;
using twitchDTO.api;

namespace twitch.ui.Controllers
{
    public class PersonneController : Controller
    {
        private DefaultDbContext context;
        private IMapper mapper;

        public PersonneController(DefaultDbContext context, IMapper mapper)
        {
            this.context = context;
            this.mapper = mapper;
        }
        public async Task<ActionResult<List<PersonneDTO>>> List()
        {
            List<Personne> persoConnect = new List<Personne>();
            var personne = await context.Personnes.ToListAsync();
            personne.ForEach(x => { if (x.IsConnected) { persoConnect.Add(x); } });
            return View("List", persoConnect.Select(mapper.Map<PersonneDTO>));
        }
        public IActionResult Edit()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        //[HttpPost]
        //public IActionResult Add(string oui)
        //{
        //    string value = this.Request.Form["oui"];
        //    return RedirectToAction("list");
        //}

        //[HttpPost]
        //public IActionResult Add(PersonneAddViewModel item)
        //{
        //    //string value = this.Request.Form["oui"];
        //    this.context.Personnes.Add(item.UnePersonne);
        //    this.context.SaveChanges();
        //    return RedirectToAction("list");
        //}

    }
}

twitch-game/twitch-game.ui/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head style="background-color : #18181B; color : #B18AEC; font-display:" Roobert","Inter","Helvetica Neue",Helvetica,Arial,sans-serif;">
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - twitch_game.ui</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/twitch_game.ui.styles.css" asp-append-version="true" />
</head>
<body style="background-color : #18181B; color : #B18AEC;">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">twitch_game.ui</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Personne" asp-action="List">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - twitch_game.ui - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>