twitch-game/twitch-simu.ui/Models/DBLecteurs/DbStreamLecteur.cs
using Microsoft.EntityFrameworkCore;
using twitch_simu.ui.Models;
using twitchDTO.api;

namespace twitch_simu.ui
{
    public class DbStreamLecteur //: ILectureDonnees<StreamDTO>
    {
        private readonly DefaultDbContext context;

        public DbStreamLecteur(DefaultDbContext context)
        {
            this.context = context;
        }

        //public List<PersonneDTO> GetAll()
        //{
        //    var query = from item in this.context.Streams.AsNoTracking()
        //                where item.IsConnected == true
        //                select new PersonneDTO(new Personne(), item.Id, item.Prenom, item.Pseudo, item.Email, item.Image,
        //                item.ListAbonnement, item.NomQuantiteKdo, item.IsConnected);
                        
                

        //    return query.ToList();
        //}
    }
}

twitch-game/twitch-simu.ui/Models/DefaultDbContext.cs
using Microsoft.EntityFrameworkCore;
using twitch.api;

namespace twitch_simu.ui
{
    public class DefaultDbContext : DbContext
    {
        public DefaultDbContext(DbContextOptions options) : base(options)
        {
        }

        protected DefaultDbContext()
        {
        }
        public DbSet<twitch.api.Stream> Streams2 { get; set; }
    }
}

twitch-game/twitch-simu.ui/Models/ErrorViewModel.cs
namespace twitch_simu.ui.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

twitch-game/twitch-simu.ui/Models/ILectureDonnees.cs
using twitchDTO.api;

namespace twitch_simu.ui.Models
{
    public interface ILectureDonnees<TData>
    {
        List<TData> GetAll();
    }
}

twitch-game/twitch-simu.ui/Models/Savers/StreamSaver.cs
using twitch_simu.ui;
using twitchDTO.api;

namespace twitch_simu.ui.Models
{
    public class StreamSaver
    {
        public readonly DefaultDbContext context;

        public StreamSaver(DefaultDbContext context)
        {
            this.context = context;
        }

        public void Save(StreamDTO stream)
        {
            this.context.Add(stream);
            this.context.SaveChanges();
        }
    }
}

twitch-game/twitch-simu.ui/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using twitch_simu.ui.Models;

namespace twitch_simu.ui.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

twitch-game/twitch-simu.ui/Controllers/StreamController.cs
using Microsoft.AspNetCore.Mvc;
using twitch_simu.ui.Models;
using twitch.api;
using twitchDTO.api;
using AutoMapper;
using Microsoft.EntityFrameworkCore;

namespace twitch_simu.ui.Controllers
{
    public class StreamController : Controller
    {
        private DefaultDbContext context;
        private IMapper mapper;

        public StreamController(DefaultDbContext context, IMapper mapper)
        {
            this.context = context;
            this.mapper = mapper;
        }

        //[HttpPost]
        //public IActionResult Create(string name)
        //{
        //    var titre = this.Request.Form["name"];
        //    var dateDebut = this.Request.Form["dateDebut"];

        //    DateTime myDate = DateTime.ParseExact(dateDebut, "yyyy-MM-ddTHH:mm",
        //                               System.Globalization.CultureInfo.InvariantCulture); //'2023-04-12T18:10


        //    StreamSaver saver = new(this.context);
        //    saver.Save(new StreamDTO(new twitch.api.Stream(), myDate, titre));



        //    return View("Create");
        //}

        [HttpPost]
        public async Task<ActionResult<List<StreamDTO>>> Create(string value)
        {
            var titre = this.Request.Form["name"];
            var dateDebut = this.Request.Form["dateDebut"];

            DateTime myDate = DateTime.ParseExact(dateDebut, "yyyy-MM-ddTHH:mm",
                                       System.Globalization.CultureInfo.InvariantCulture); //'2023-04-12T18:10

            var nstream = new StreamDTO(titre, myDate);
            var stream = mapper.Map<twitch.api.Stream>(nstream);
            this.context.Streams2.Add(stream);
            await this.context.SaveChangesAsync();

            return View("Create");
        }

        [HttpGet]
        public async Task<ActionResult<List<StreamDTO>>> Create()
        {
            var stream = await context.Streams2.ToListAsync();

            return View("Create", stream.Select(mapper.Map<StreamDTO>));
        }


        //[HttpPost]
        //public IActionResult Add(string oui)
        //{
        //    string value = this.Request.Form["oui"];
        //    return RedirectToAction("list");
        //}

        //[HttpPost]
        //public IActionResult Add(PersonneAddViewModel item)
        //{
        //    //string value = this.Request.Form["oui"];
        //    this.context.Personnes.Add(item.UnePersonne);
        //    this.context.SaveChanges();
        //    return RedirectToAction("list");
        //}

    }
}

twitch-game/twitch-simu.ui/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    <a style="background-color: #b18aec" type="button" class="btn btn-dark" asp-area="" asp-controller="Stream" asp-action="Create">Nouveau Stream !</a>
</div>

twitch-game/twitch-simu.ui/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - twitch_simu.ui</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/twitch_simu.ui.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">twitch_simu.ui</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - twitch_simu.ui - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

twitch-game/twitch-simu.ui/Views/Stream/Create.cshtml
<form asp-action="Create" asp-controller="Stream" method="post">
    <input type="text" name="titreStream"/>
    <input type="datetime-local" name="dateDebut"/>

    <button type="submit">Ajouter</button>


</form>


@foreach (var item in Model)
{
    <div>@item.Name</div>
}